In [2]:
%pip install kaggle sqlalchemy pymysql psycopg2-binary pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\raveena\appdata\roaming\python\python313\site-packages (2.2.2)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\raveena\appdata\roaming\python\python313\site-packages (1.2.0)
Requirement already satisfied: psycopg2-binary in c:\users\raveena\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: pandas in c:\users\raveena\appdata\roaming\python\python313\site-packages (3.0.0)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (0.1.30)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\programdata\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in c:\programdata\anaconda3\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (2.6.2)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from pandas) (2.4.0)
Requirement already satisfied: tzdata in c:\users\raveena\appdata\roaming\python\python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: webencodings in c:\users\raveena\appdata\roaming\python\python313\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: text-unidecode>=1.3 in c:\programdata\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from requests->kaggle) (2025.11.12)
Requirement already satisfied: colorama in c:\users\raveena\appdata\roaming\python\python313\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\raveena\appdata\roaming\python\python313\site-packages (2.2.2)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (0.1.30)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\programdata\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in c:\programdata\anaconda3\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from kaggle) (2.6.2)
Requirement already satisfied: webencodings in c:\users\raveena\appdata\roaming\python\python313\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\programdata\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: six>=1.5 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\programdata\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from requests->kaggle) (2025.11.12)
Requirement already satisfied: colorama in c:\users\raveena\appdata\roaming\python\python313\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip list

Package                           Version
--------------------------------- --------------------
aiobotocore                       2.25.0
aiodns                            3.5.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.13.2
aioitertools                      0.12.0
aiosignal                         1.4.0
alabaster                         0.7.16
altair                            5.5.0
anaconda-anon-usage               0.7.5
anaconda-auth                     0.12.3
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.7.0
anaconda-client                   1.14.0
anaconda-navigator                2.7.0
anaconda-project                  0.11.1
annotated-types                   0.7.0
anyio                             4.12.0
appdirs                           1.4.4
archspec                          0.2.5
argon2-cffi                       21.3.0
argon2-cffi-bindings              25.1.0
arrow                             1.4.0
astroid                           3.3.11
astropy                           7.1.1
astropy-iers-data                 0.2025.11.10.0.38.31
asttokens                         3.0.0
async-lru                         2.0.5
asyncssh                          2.21.1
atomicwrites                      1.4.0
attrs                             25.4.0
Automat                           24.8.1
autopep8                          2.0.4
babel                             2.17.0
bcrypt                            5.0.0
beautifulsoup4                    4.13.5
binaryornot                       0.4.4
black                             25.9.0
bleach                            6.3.0
blinker                           1.9.0
bokeh                             3.8.0
boltons                           25.0.0
botocore                          1.40.46
Bottleneck                        1.4.2
brotli                            1.2.0
brotlicffi                        1.1.0.0
cachetools                        5.5.1
cattrs                            25.3.0
certifi                           2025.11.12
cffi                              2.0.0
chardet                           5.2.0
charset-normalizer                3.4.4
click                             8.3.1
cloudpickle                       3.1.1
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.3
conda                             25.11.1
conda-anaconda-telemetry          0.3.0
conda-anaconda-tos                0.2.2
conda-build                       25.11.1
conda-content-trust               0.2.0
conda_index                       0.7.0
conda-libmamba-solver             25.11.0
conda-pack                        0.8.1
conda-package-handling            2.4.0
conda_package_streaming           0.12.0
conda-repo-cli                    1.0.173
constantly                        23.10.4
contourpy                         1.3.3
cookiecutter                      2.6.0
cryptography                      46.0.3
cssselect                         1.2.0
cssselect2                        0.8.0
cycler                            0.11.0
dask                              2025.11.0
datashader                        0.18.2
debugpy                           1.8.16
decorator                         5.2.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.4.0
distributed                       2025.11.0
distro                            1.9.0
docstring-to-markdown             0.17
docutils                          0.21.2
et_xmlfile                        2.0.0
evalidate                         2.0.3
executing                         2.2.1
fastjsonschema                    2.21.2
filelock                          3.20.0
flake8                            7.1.1
Flask                             3.1.2
fonttools                         4.61.1
frozendict                        2.4.6
frozenlist                        1.8.0
fsspec                            2025.10.0
gitdb                             4.0.12
GitPython                         3.1.45
gmpy2                             2.2.1
greenlet                          3.2.4
h11                               0.16.0
h5py                              3.15.1
HeapDict                          1.0.1
holoviews                         1.22.0
html5lib                          1.1
httpcore                          1.0.9
httpx                             0.28.1
hvplot                            0.12.1
hyperlink                         21.0.0
idna                              3.11
ImageIO                           2.37.2
imagesize                         1.4.1
imbalanced-learn                  0.14.0
importlib_metadata                8.7.0
incremental                       24.7.2
inflection                        0.5.1
iniconfig                         2.1.0
intake                            2.0.8
intervaltree                      3.1.0
ipykernel                         6.31.0
ipympl                            0.9.7
ipython                           9.7.0
ipython_pygments_lexers           1.1.1
ipywidgets                        8.1.7
isort                             6.1.0
itemadapter                       0.12.1
itemloaders                       1.3.2
itsdangerous                      2.2.0
jaraco.classes                    3.4.0
jaraco.context                    0.0.0
jaraco.functools                  4.1.0
jedi                              0.19.2
jellyfish                         1.2.1
Jinja2                            3.1.6
jiter                             0.12.0
jmespath                          1.0.1
joblib                            1.5.2
json5                             0.12.1
jsonpatch                         1.33
jsonpointer                       3.0.0
jsonschema                        4.25.0
jsonschema-specifications         2025.9.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.8.1
jupyter-events                    0.12.0
jupyter-lsp                       2.2.5
jupyter_server                    2.16.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.4.7
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.28.0
jupyterlab_widgets                3.0.15
jupytext                          1.19.4
kaggle                            2.2.2
kagglesdk                         0.1.30
keyring                           25.7.0
kiwisolver                        1.4.9
lazy_loader                       0.4
lckr_jupyterlab_variableinspector 3.2.4
libarchive-c                      5.1
libmambapy                        2.3.2
lief                              0.16.4
linkify-it-py                     2.0.3
llvmlite                          0.45.1
lmdb                              1.7.5
locket                            1.0.0
lsprotocol                        2025.0.0
lxml                              6.0.2
lz4                               4.4.5
Markdown                          3.8
markdown-it-py                    2.2.0
MarkupSafe                        3.0.3
matplotlib                        3.10.6
matplotlib-inline                 0.2.1
mccabe                            0.7.0
mdit-py-plugins                   0.5.0
mdurl                             0.1.2
menuinst                          2.4.2
mistune                           3.1.2
mkl_fft                           2.1.1
mkl_random                        1.3.0
mkl-service                       2.5.2
more-itertools                    10.8.0
mpi4py                            4.0.3
mpmath                            1.3.0
msgpack                           1.1.1
multidict                         6.7.0
multipledispatch                  1.0.0
mypy                              1.17.1
mypy_extensions                   1.0.0
narwhals                          2.7.0
navigator-updater                 0.6.0
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest_asyncio                      1.6.0
networkx                          3.5
nltk                              3.9.2
notebook                          7.4.5
notebook_shim                     0.2.4
numba                             0.62.1
numexpr                           2.14.1
numpy                             2.4.0
numpydoc                          1.9.0
openai                            2.14.0
openpyxl                          3.1.5
overrides                         7.7.0
packaging                         25.0
pandas                            3.0.0
pandocfilters                     1.5.1
panel                             1.8.3
param                             2.3.0
parsel                            1.10.0
parso                             0.8.5
partd                             1.4.2
pathspec                          0.12.1
patsy                             1.0.1
pexpect                           4.9.0
pickleshare                       0.7.5
pillow                            12.0.0
pip                               25.3
pkce                              1.0.3
pkginfo                           1.12.1.2
platformdirs                      4.5.0
plotly                            6.3.0
pluggy                            1.5.0
prometheus_client                 0.21.1
prompt_toolkit                    3.0.52
propcache                         0.3.1
Protego                           0.4.0
protobuf                          5.29.3
psutil                            7.0.0
psycopg2-binary                   2.9.12
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyarrow                           21.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.2
pycares                           4.10.0
pycodestyle                       2.12.1
pycosat                           0.6.6
pycparser                         2.23
pyct                              0.6.0
pycurl                            7.45.7
pydantic                          2.12.5
pydantic_core                     2.41.5
pydantic-settings                 2.12.0
PyDispatcher                      2.0.7
pydocstyle                        6.3.0
pydyf                             0.12.1
pyerfa                            2.0.1.5
pyflakes                          3.2.0
PyGithub                          2.8.1
Pygments                          2.19.2
PyJWT                             2.10.1
pylint                            3.3.8
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyMySQL                           1.2.0
PyNaCl                            1.6.0
pyodbc                            5.3.0
pyOpenSSL                         25.3.0
pyparsing                         3.2.5
pyphen                            0.17.2
PyQt5                             5.15.11
PyQt5_sip                         12.17.0
PyQtWebEngine                     5.15.7
PySide6                           6.9.2
PySocks                           1.7.1
pytest                            8.4.2
python-dateutil                   2.9.0.post0
python-docx                       1.2.0
python-dotenv                     1.1.0
python-json-logger                3.2.1
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-ruff                   2.3.0
python-lsp-server                 1.13.1
python-slugify                    8.0.4
pytokens                          0.3.0
pytoolconfig                      1.2.6
pytz                              2025.2
pyuca                             1.2
pyviz_comms                       3.0.6
PyWavelets                        1.9.0
pywin32                           311
pywin32-ctypes                    0.2.2
pywinpty                          2.0.15
PyYAML                            6.0.3
pyzmq                             27.1.0
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.4.0
qtconsole                         5.7.0
QtPy                              2.4.3
queuelib                          1.8.0
readchar                          4.2.1
referencing                       0.37.0
regex                             2025.9.1
requests                          2.32.5
requests-file                     2.1.0
requests-toolbelt                 1.0.0
rfc3339_validator                 0.1.4
rfc3986_validator                 0.1.1
rich                              14.2.0
roman-numerals-py                 3.1.0
rope                              1.14.0
rpds-py                           0.28.0
rtree                             1.4.1
ruamel.yaml                       0.18.16
ruamel.yaml.clib                  0.2.14
ruamel_yaml_conda                 0.17.21
ruff                              0.12.0
s3fs                              2025.10.0
scikit-image                      0.25.2
scikit-learn                      1.7.2
scipy                             1.16.3
Scrapy                            2.13.3
seaborn                           0.13.2
semver                            3.0.4
Send2Trash                        1.8.2
service-identity                  24.2.0
setuptools                        80.9.0
shellingham                       1.5.4
shiboken6                         6.9.2
sip                               6.12.0
six                               1.17.0
smmap                             4.0.0
sniffio                           1.3.1
snowballstemmer                   3.0.1
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            8.2.3
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
spyder                            6.1.0
spyder-kernels                    3.1.1
SQLAlchemy                        2.0.43
stack_data                        0.6.3
statsmodels                       0.14.5
streamlit                         1.51.0
superqt                           0.7.6
sympy                             1.14.0
tables                            3.10.2
tabulate                          0.9.0
tblib                             3.1.0
tenacity                          9.1.2
terminado                         0.18.1
text-unidecode                    1.3
textdistance                      4.6.3
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2025.10.4
tinycss2                          1.5.1
tinyhtml5                         2.0.0
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.2.1
tomlkit                           0.13.3
toolz                             1.0.0
tornado                           6.5.1
tqdm                              4.67.1
traitlets                         5.14.3
truststore                        0.10.1
Twisted                           25.5.0
twisted-iocpsupport               1.0.2
typer                             0.20.0
typer-slim                        0.20.0
typing_extensions                 4.15.0
typing-inspection                 0.4.2
tzdata                            2025.3
uc-micro-py                       1.0.3
ujson                             5.11.0
urllib3                           2.6.2
w3lib                             2.3.1
watchdog                          6.0.0
wcwidth                           0.2.13
weasyprint                        67.0
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.1.4
whatthepatch                      1.0.7
wheel                             0.45.1
widgetsnbextension                4.0.14
win_inet_pton                     1.1.0
winloop                           0.3.1
wrapt                             1.17.0
xarray                            2025.10.1
xlwings                           0.33.15
xyzservices                       2025.4.0
yapf                              0.43.0
yarl                              1.22.0
zict                              3.0.0
zipp                              3.23.0
zope.interface                    8.0.1
zopfli                            0.4.0
zstandard                         0.24.0
Note: you may need to restart the kernel to use updated packages.

In [11]:
!python -m kaggle datasets download -d najir0123/walmart-10k-sales-datasets

Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets
License(s): MIT
Downloading walmart-10k-sales-datasets.zip to C:\Users\Raveena\OneDrive\Desktop\project_walmart

  0%|          | 0.00/143k [00:00<?, ?B/s]
100%|##########| 143k/143k [00:00<00:00, 180kB/s]
100%|##########| 143k/143k [00:00<00:00, 180kB/s]

In [14]:
import zipfile

with zipfile.ZipFile('walmart-10k-sales-datasets.zip', 'r') as zip_ref:
    zip_ref.extractall('.')  # This extracts everything into your current folder

print("Unzipped successfully!")

Unzipped successfully!

In [18]:
import os
os.listdir('.')

['.ipynb_checkpoints',
 'project.ipynb',
 'walmart-10k-sales-datasets.zip',
 'walmart.csv']

In [4]:
import pandas as pd
df = pd.read_csv('walmart.csv')
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [7]:
#mysql tool kit
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\raveena\appdata\roaming\python\python313\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\raveena\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)

In [8]:
!pip list

Package                           Version
--------------------------------- --------------------
aiobotocore                       2.25.0
aiodns                            3.5.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.13.2
aioitertools                      0.12.0
aiosignal                         1.4.0
alabaster                         0.7.16
altair                            5.5.0
anaconda-anon-usage               0.7.5
anaconda-auth                     0.12.3
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.7.0
anaconda-client                   1.14.0
anaconda-navigator                2.7.0
anaconda-project                  0.11.1
annotated-types                   0.7.0
anyio                             4.12.0
appdirs                           1.4.4
archspec                          0.2.5
argon2-cffi                       21.3.0
argon2-cffi-bindings              25.1.0
arrow                             1.4.0
astroid                           3.3.11
astropy                           7.1.1
astropy-iers-data                 0.2025.11.10.0.38.31
asttokens                         3.0.0
async-lru                         2.0.5
asyncssh                          2.21.1
atomicwrites                      1.4.0
attrs                             25.4.0
Automat                           24.8.1
autopep8                          2.0.4
babel                             2.17.0
bcrypt                            5.0.0
beautifulsoup4                    4.13.5
binaryornot                       0.4.4
black                             25.9.0
bleach                            6.3.0
blinker                           1.9.0
bokeh                             3.8.0
boltons                           25.0.0
botocore                          1.40.46
Bottleneck                        1.4.2
brotli                            1.2.0
brotlicffi                        1.1.0.0
cachetools                        5.5.1
cattrs                            25.3.0
certifi                           2025.11.12
cffi                              2.0.0
chardet                           5.2.0
charset-normalizer                3.4.4
click                             8.3.1
cloudpickle                       3.1.1
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.3
conda                             25.11.1
conda-anaconda-telemetry          0.3.0
conda-anaconda-tos                0.2.2
conda-build                       25.11.1
conda-content-trust               0.2.0
conda_index                       0.7.0
conda-libmamba-solver             25.11.0
conda-pack                        0.8.1
conda-package-handling            2.4.0
conda_package_streaming           0.12.0
conda-repo-cli                    1.0.173
constantly                        23.10.4
contourpy                         1.3.3
cookiecutter                      2.6.0
cryptography                      46.0.3
cssselect                         1.2.0
cssselect2                        0.8.0
cycler                            0.11.0
dask                              2025.11.0
datashader                        0.18.2
debugpy                           1.8.16
decorator                         5.2.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.4.0
distributed                       2025.11.0
distro                            1.9.0
docstring-to-markdown             0.17
docutils                          0.21.2
et_xmlfile                        2.0.0
evalidate                         2.0.3
executing                         2.2.1
fastjsonschema                    2.21.2
filelock                          3.20.0
flake8                            7.1.1
Flask                             3.1.2
fonttools                         4.61.1
frozendict                        2.4.6
frozenlist                        1.8.0
fsspec                            2025.10.0
gitdb                             4.0.12
GitPython                         3.1.45
gmpy2                             2.2.1
greenlet                          3.2.4
h11                               0.16.0
h5py                              3.15.1
HeapDict                          1.0.1
holoviews                         1.22.0
html5lib                          1.1
httpcore                          1.0.9
httpx                             0.28.1
hvplot                            0.12.1
hyperlink                         21.0.0
idna                              3.11
ImageIO                           2.37.2
imagesize                         1.4.1
imbalanced-learn                  0.14.0
importlib_metadata                8.7.0
incremental                       24.7.2
inflection                        0.5.1
iniconfig                         2.1.0
intake                            2.0.8
intervaltree                      3.1.0
ipykernel                         6.31.0
ipympl                            0.9.7
ipython                           9.7.0
ipython_pygments_lexers           1.1.1
ipywidgets                        8.1.7
isort                             6.1.0
itemadapter                       0.12.1
itemloaders                       1.3.2
itsdangerous                      2.2.0
jaraco.classes                    3.4.0
jaraco.context                    0.0.0
jaraco.functools                  4.1.0
jedi                              0.19.2
jellyfish                         1.2.1
Jinja2                            3.1.6
jiter                             0.12.0
jmespath                          1.0.1
joblib                            1.5.2
json5                             0.12.1
jsonpatch                         1.33
jsonpointer                       3.0.0
jsonschema                        4.25.0
jsonschema-specifications         2025.9.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.8.1
jupyter-events                    0.12.0
jupyter-lsp                       2.2.5
jupyter_server                    2.16.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.4.7
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.28.0
jupyterlab_widgets                3.0.15
jupytext                          1.19.4
kaggle                            2.2.2
kagglesdk                         0.1.30
keyring                           25.7.0
kiwisolver                        1.4.9
lazy_loader                       0.4
lckr_jupyterlab_variableinspector 3.2.4
libarchive-c                      5.1
libmambapy                        2.3.2
lief                              0.16.4
linkify-it-py                     2.0.3
llvmlite                          0.45.1
lmdb                              1.7.5
locket                            1.0.0
lsprotocol                        2025.0.0
lxml                              6.0.2
lz4                               4.4.5
Markdown                          3.8
markdown-it-py                    2.2.0
MarkupSafe                        3.0.3
matplotlib                        3.10.6
matplotlib-inline                 0.2.1
mccabe                            0.7.0
mdit-py-plugins                   0.5.0
mdurl                             0.1.2
menuinst                          2.4.2
mistune                           3.1.2
mkl_fft                           2.1.1
mkl_random                        1.3.0
mkl-service                       2.5.2
more-itertools                    10.8.0
mpi4py                            4.0.3
mpmath                            1.3.0
msgpack                           1.1.1
multidict                         6.7.0
multipledispatch                  1.0.0
mypy                              1.17.1
mypy_extensions                   1.0.0
narwhals                          2.7.0
navigator-updater                 0.6.0
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest_asyncio                      1.6.0
networkx                          3.5
nltk                              3.9.2
notebook                          7.4.5
notebook_shim                     0.2.4
numba                             0.62.1
numexpr                           2.14.1
numpy                             2.4.0
numpydoc                          1.9.0
openai                            2.14.0
openpyxl                          3.1.5
overrides                         7.7.0
packaging                         25.0
pandas                            3.0.0
pandocfilters                     1.5.1
panel                             1.8.3
param                             2.3.0
parsel                            1.10.0
parso                             0.8.5
partd                             1.4.2
pathspec                          0.12.1
patsy                             1.0.1
pexpect                           4.9.0
pickleshare                       0.7.5
pillow                            12.0.0
pip                               25.3
pkce                              1.0.3
pkginfo                           1.12.1.2
platformdirs                      4.5.0
plotly                            6.3.0
pluggy                            1.5.0
prometheus_client                 0.21.1
prompt_toolkit                    3.0.52
propcache                         0.3.1
Protego                           0.4.0
protobuf                          5.29.3
psutil                            7.0.0
psycopg2-binary                   2.9.12
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyarrow                           21.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.2
pycares                           4.10.0
pycodestyle                       2.12.1
pycosat                           0.6.6
pycparser                         2.23
pyct                              0.6.0
pycurl                            7.45.7
pydantic                          2.12.5
pydantic_core                     2.41.5
pydantic-settings                 2.12.0
PyDispatcher                      2.0.7
pydocstyle                        6.3.0
pydyf                             0.12.1
pyerfa                            2.0.1.5
pyflakes                          3.2.0
PyGithub                          2.8.1
Pygments                          2.19.2
PyJWT                             2.10.1
pylint                            3.3.8
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyMySQL                           1.2.0
PyNaCl                            1.6.0
pyodbc                            5.3.0
pyOpenSSL                         25.3.0
pyparsing                         3.2.5
pyphen                            0.17.2
PyQt5                             5.15.11
PyQt5_sip                         12.17.0
PyQtWebEngine                     5.15.7
PySide6                           6.9.2
PySocks                           1.7.1
pytest                            8.4.2
python-dateutil                   2.9.0.post0
python-docx                       1.2.0
python-dotenv                     1.1.0
python-json-logger                3.2.1
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-ruff                   2.3.0
python-lsp-server                 1.13.1
python-slugify                    8.0.4
pytokens                          0.3.0
pytoolconfig                      1.2.6
pytz                              2025.2
pyuca                             1.2
pyviz_comms                       3.0.6
PyWavelets                        1.9.0
pywin32                           311
pywin32-ctypes                    0.2.2
pywinpty                          2.0.15
PyYAML                            6.0.3
pyzmq                             27.1.0
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.4.0
qtconsole                         5.7.0
QtPy                              2.4.3
queuelib                          1.8.0
readchar                          4.2.1
referencing                       0.37.0
regex                             2025.9.1
requests                          2.32.5
requests-file                     2.1.0
requests-toolbelt                 1.0.0
rfc3339_validator                 0.1.4
rfc3986_validator                 0.1.1
rich                              14.2.0
roman-numerals-py                 3.1.0
rope                              1.14.0
rpds-py                           0.28.0
rtree                             1.4.1
ruamel.yaml                       0.18.16
ruamel.yaml.clib                  0.2.14
ruamel_yaml_conda                 0.17.21
ruff                              0.12.0
s3fs                              2025.10.0
scikit-image                      0.25.2
scikit-learn                      1.7.2
scipy                             1.16.3
Scrapy                            2.13.3
seaborn                           0.13.2
semver                            3.0.4
Send2Trash                        1.8.2
service-identity                  24.2.0
setuptools                        80.9.0
shellingham                       1.5.4
shiboken6                         6.9.2
sip                               6.12.0
six                               1.17.0
smmap                             4.0.0
sniffio                           1.3.1
snowballstemmer                   3.0.1
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            8.2.3
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
spyder                            6.1.0
spyder-kernels                    3.1.1
SQLAlchemy                        2.0.43
stack_data                        0.6.3
statsmodels                       0.14.5
streamlit                         1.51.0
superqt                           0.7.6
sympy                             1.14.0
tables                            3.10.2
tabulate                          0.9.0
tblib                             3.1.0
tenacity                          9.1.2
terminado                         0.18.1
text-unidecode                    1.3
textdistance                      4.6.3
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2025.10.4
tinycss2                          1.5.1
tinyhtml5                         2.0.0
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.2.1
tomlkit                           0.13.3
toolz                             1.0.0
tornado                           6.5.1
tqdm                              4.67.1
traitlets                         5.14.3
truststore                        0.10.1
Twisted                           25.5.0
twisted-iocpsupport               1.0.2
typer                             0.20.0
typer-slim                        0.20.0
typing_extensions                 4.15.0
typing-inspection                 0.4.2
tzdata                            2025.3
uc-micro-py                       1.0.3
ujson                             5.11.0
urllib3                           2.6.2
w3lib                             2.3.1
watchdog                          6.0.0
wcwidth                           0.2.13
weasyprint                        67.0
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.1.4
whatthepatch                      1.0.7
wheel                             0.45.1
widgetsnbextension                4.0.14
win_inet_pton                     1.1.0
winloop                           0.3.1
wrapt                             1.17.0
xarray                            2025.10.1
xlwings                           0.33.15
xyzservices                       2025.4.0
yapf                              0.43.0
yarl                              1.22.0
zict                              3.0.0
zipp                              3.23.0
zope.interface                    8.0.1
zopfli                            0.4.0
zstandard                         0.24.0

In [10]:
from sqlalchemy import create_engine

In [5]:
df.shape

(10051, 11)

In [6]:
df.describe

<bound method NDFrame.describe of        invoice_id   Branch         City                category unit_price  \
0               1  WALM003  San Antonio       Health and beauty     $74.69
1               2  WALM048    Harlingen  Electronic accessories     $15.28
2               3  WALM067  Haltom City      Home and lifestyle     $46.33
3               4  WALM064      Bedford       Health and beauty     $58.22
4               5  WALM013       Irving       Sports and travel     $86.31
...           ...      ...          ...                     ...        ...
10046        9996  WALM056      Rowlett     Fashion accessories        $37
10047        9997  WALM030   Richardson      Home and lifestyle        $58
10048        9998  WALM050     Victoria     Fashion accessories        $52
10049        9999  WALM032        Tyler      Home and lifestyle        $79
10050       10000  WALM069     Rockwall     Fashion accessories        $62

       quantity      date      time payment_method  rating  profit_margin
0           7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1           5.0  08/03/19  10:29:00           Cash     9.6           0.48
2           7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3           8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4           7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...         ...       ...       ...            ...     ...            ...
10046       3.0  03/08/23  10:10:00           Cash     3.0           0.33
10047       2.0  22/02/21  14:20:00           Cash     7.0           0.48
10048       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
10049       2.0  25/02/21  12:25:00           Cash     7.0           0.48
10050       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[10051 rows x 11 columns]>

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 1.4 MB

In [25]:
#for finding the duplicates
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
total             0
dtype: int64

In [27]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [17]:
#dropping the missing values columns
df.dropna(inplace=True)

In [18]:
df.shape

(10020, 11)

In [19]:
df['unit_price']=df['unit_price'].str.replace('$',' ').astype(float)

In [20]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [21]:
#verifying the unit_price datatype
df.info()

<class 'pandas.DataFrame'>
Index: 10020 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10020 non-null  int64
 1   Branch          10020 non-null  str
 2   City            10020 non-null  str
 3   category        10020 non-null  str
 4   unit_price      10020 non-null  float64
 5   quantity        10020 non-null  float64
 6   date            10020 non-null  str
 7   time            10020 non-null  str
 8   payment_method  10020 non-null  str
 9   rating          10020 non-null  float64
 10  profit_margin   10020 non-null  float64
dtypes: float64(4), int64(1), str(6)
memory usage: 1.5 MB

In [51]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [23]:
df['total']=df['unit_price']*df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [12]:
# mysql
# host=localhost
# port=3306
# user=root
# password='root'

In [28]:
df.shape

(9969, 12)

In [30]:
df.to_csv('walmart_clean_data.csv', index=False)

In [32]:
help(create_engine)

Help on function create_engine in module sqlalchemy.engine.create:

create_engine(url: 'Union[str, _url.URL]', **kwargs: 'Any') -> 'Engine'
    Create a new :class:`_engine.Engine` instance.

    The standard calling form is to send the :ref:`URL <database_urls>` as the
    first positional argument, usually a string
    that indicates database dialect and connection arguments::

        engine = create_engine("postgresql+psycopg2://scott:tiger@localhost/test")

    .. note::

        Please review :ref:`database_urls` for general guidelines in composing
        URL strings.  In particular, special characters, such as those often
        part of passwords, must be URL encoded to be properly parsed.

    Additional keyword arguments may then follow it which
    establish various options on the resulting :class:`_engine.Engine`
    and its underlying :class:`.Dialect` and :class:`_pool.Pool`
    constructs::

        engine = create_engine(
            "mysql+mysqldb://scott:tiger@hostname/dbname",
            pool_recycle=3600,
            echo=True,
        )

    The string form of the URL is
    ``dialect[+driver]://user:password@host/dbname[?key=value..]``, where
    ``dialect`` is a database name such as ``mysql``, ``oracle``,
    ``postgresql``, etc., and ``driver`` the name of a DBAPI, such as
    ``psycopg2``, ``pyodbc``, ``cx_oracle``, etc.  Alternatively,
    the URL can be an instance of :class:`~sqlalchemy.engine.url.URL`.

    ``**kwargs`` takes a wide variety of options which are routed
    towards their appropriate components.  Arguments may be specific to
    the :class:`_engine.Engine`, the underlying :class:`.Dialect`,
    as well as the
    :class:`_pool.Pool`.  Specific dialects also accept keyword arguments that
    are unique to that dialect.   Here, we describe the parameters
    that are common to most :func:`_sa.create_engine()` usage.

    Once established, the newly resulting :class:`_engine.Engine` will
    request a connection from the underlying :class:`_pool.Pool` once
    :meth:`_engine.Engine.connect` is called, or a method which depends on it
    such as :meth:`_engine.Engine.execute` is invoked.   The
    :class:`_pool.Pool` in turn
    will establish the first actual DBAPI connection when this request
    is received.   The :func:`_sa.create_engine` call itself does **not**
    establish any actual DBAPI connections directly.

    .. seealso::

        :doc:`/core/engines`

        :doc:`/dialects/index`

        :ref:`connections_toplevel`

    :param connect_args: a dictionary of options which will be
        passed directly to the DBAPI's ``connect()`` method as
        additional keyword arguments.  See the example
        at :ref:`custom_dbapi_args`.

    :param creator: a callable which returns a DBAPI connection.
        This creation function will be passed to the underlying
        connection pool and will be used to create all new database
        connections. Usage of this function causes connection
        parameters specified in the URL argument to be bypassed.

        This hook is not as flexible as the newer
        :meth:`_events.DialectEvents.do_connect` hook which allows complete
        control over how a connection is made to the database, given the full
        set of URL arguments and state beforehand.

        .. seealso::

            :meth:`_events.DialectEvents.do_connect` - event hook that allows
            full control over DBAPI connection mechanics.

            :ref:`custom_dbapi_args`

    :param echo=False: if True, the Engine will log all statements
        as well as a ``repr()`` of their parameter lists to the default log
        handler, which defaults to ``sys.stdout`` for output.   If set to the
        string ``"debug"``, result rows will be printed to the standard output
        as well. The ``echo`` attribute of ``Engine`` can be modified at any
        time to turn logging on and off; direct control of logging is also
        available using the standard Python ``logging`` module.

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.


    :param echo_pool=False: if True, the connection pool will log
        informational output such as when connections are invalidated
        as well as when connections are recycled to the default log handler,
        which defaults to ``sys.stdout`` for output.   If set to the string
        ``"debug"``, the logging will include pool checkouts and checkins.
        Direct control of logging is also available using the standard Python
        ``logging`` module.

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.


    :param empty_in_strategy:   No longer used; SQLAlchemy now uses
        "empty set" behavior for IN in all cases.

    :param enable_from_linting: defaults to True.  Will emit a warning
        if a given SELECT statement is found to have un-linked FROM elements
        which would cause a cartesian product.

        .. versionadded:: 1.4

        .. seealso::

            :ref:`change_4737`

    :param execution_options: Dictionary execution options which will
        be applied to all connections.  See
        :meth:`~sqlalchemy.engine.Connection.execution_options`

    :param future: Use the 2.0 style :class:`_engine.Engine` and
        :class:`_engine.Connection` API.

        As of SQLAlchemy 2.0, this parameter is present for backwards
        compatibility only and must remain at its default value of ``True``.

        The :paramref:`_sa.create_engine.future` parameter will be
        deprecated in a subsequent 2.x release and eventually removed.

        .. versionadded:: 1.4

        .. versionchanged:: 2.0 All :class:`_engine.Engine` objects are
           "future" style engines and there is no longer a ``future=False``
           mode of operation.

        .. seealso::

            :ref:`migration_20_toplevel`

    :param hide_parameters: Boolean, when set to True, SQL statement parameters
        will not be displayed in INFO logging nor will they be formatted into
        the string representation of :class:`.StatementError` objects.

        .. versionadded:: 1.3.8

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.

    :param implicit_returning=True:  Legacy parameter that may only be set
        to True. In SQLAlchemy 2.0, this parameter does nothing. In order to
        disable "implicit returning" for statements invoked by the ORM,
        configure this on a per-table basis using the
        :paramref:`.Table.implicit_returning` parameter.


    :param insertmanyvalues_page_size: number of rows to format into an
     INSERT statement when the statement uses "insertmanyvalues" mode, which is
     a paged form of bulk insert that is used for many backends when using
     :term:`executemany` execution typically in conjunction with RETURNING.
     Defaults to 1000, but may also be subject to dialect-specific limiting
     factors which may override this value on a per-statement basis.

     .. versionadded:: 2.0

     .. seealso::

        :ref:`engine_insertmanyvalues`

        :ref:`engine_insertmanyvalues_page_size`

        :paramref:`_engine.Connection.execution_options.insertmanyvalues_page_size`

    :param isolation_level: optional string name of an isolation level
        which will be set on all new connections unconditionally.
        Isolation levels are typically some subset of the string names
        ``"SERIALIZABLE"``, ``"REPEATABLE READ"``,
        ``"READ COMMITTED"``, ``"READ UNCOMMITTED"`` and ``"AUTOCOMMIT"``
        based on backend.

        The :paramref:`_sa.create_engine.isolation_level` parameter is
        in contrast to the
        :paramref:`.Connection.execution_options.isolation_level`
        execution option, which may be set on an individual
        :class:`.Connection`, as well as the same parameter passed to
        :meth:`.Engine.execution_options`, where it may be used to create
        multiple engines with different isolation levels that share a common
        connection pool and dialect.

        .. versionchanged:: 2.0 The
           :paramref:`_sa.create_engine.isolation_level`
           parameter has been generalized to work on all dialects which support
           the concept of isolation level, and is provided as a more succinct,
           up front configuration switch in contrast to the execution option
           which is more of an ad-hoc programmatic option.

        .. seealso::

            :ref:`dbapi_autocommit`

    :param json_deserializer: for dialects that support the
        :class:`_types.JSON`
        datatype, this is a Python callable that will convert a JSON string
        to a Python object.  By default, the Python ``json.loads`` function is
        used.

        .. versionchanged:: 1.3.7  The SQLite dialect renamed this from
           ``_json_deserializer``.

    :param json_serializer: for dialects that support the :class:`_types.JSON`
        datatype, this is a Python callable that will render a given object
        as JSON.   By default, the Python ``json.dumps`` function is used.

        .. versionchanged:: 1.3.7  The SQLite dialect renamed this from
           ``_json_serializer``.


    :param label_length=None: optional integer value which limits
        the size of dynamically generated column labels to that many
        characters. If less than 6, labels are generated as
        "_(counter)". If ``None``, the value of
        ``dialect.max_identifier_length``, which may be affected via the
        :paramref:`_sa.create_engine.max_identifier_length` parameter,
        is used instead.   The value of
        :paramref:`_sa.create_engine.label_length`
        may not be larger than that of
        :paramref:`_sa.create_engine.max_identfier_length`.

        .. seealso::

            :paramref:`_sa.create_engine.max_identifier_length`

    :param logging_name:  String identifier which will be used within
        the "name" field of logging records generated within the
        "sqlalchemy.engine" logger. Defaults to a hexstring of the
        object's id.

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.

            :paramref:`_engine.Connection.execution_options.logging_token`

    :param max_identifier_length: integer; override the max_identifier_length
        determined by the dialect.  if ``None`` or zero, has no effect.  This
        is the database's configured maximum number of characters that may be
        used in a SQL identifier such as a table name, column name, or label
        name. All dialects determine this value automatically, however in the
        case of a new database version for which this value has changed but
        SQLAlchemy's dialect has not been adjusted, the value may be passed
        here.

        .. versionadded:: 1.3.9

        .. seealso::

            :paramref:`_sa.create_engine.label_length`

    :param max_overflow=10: the number of connections to allow in
        connection pool "overflow", that is connections that can be
        opened above and beyond the pool_size setting, which defaults
        to five. this is only used with :class:`~sqlalchemy.pool.QueuePool`.

    :param module=None: reference to a Python module object (the module
        itself, not its string name).  Specifies an alternate DBAPI module to
        be used by the engine's dialect.  Each sub-dialect references a
        specific DBAPI which will be imported before first connect.  This
        parameter causes the import to be bypassed, and the given module to
        be used instead. Can be used for testing of DBAPIs as well as to
        inject "mock" DBAPI implementations into the :class:`_engine.Engine`.

    :param paramstyle=None: The `paramstyle <https://legacy.python.org/dev/peps/pep-0249/#paramstyle>`_
        to use when rendering bound parameters.  This style defaults to the
        one recommended by the DBAPI itself, which is retrieved from the
        ``.paramstyle`` attribute of the DBAPI.  However, most DBAPIs accept
        more than one paramstyle, and in particular it may be desirable
        to change a "named" paramstyle into a "positional" one, or vice versa.
        When this attribute is passed, it should be one of the values
        ``"qmark"``, ``"numeric"``, ``"named"``, ``"format"`` or
        ``"pyformat"``, and should correspond to a parameter style known
        to be supported by the DBAPI in use.

    :param pool=None: an already-constructed instance of
        :class:`~sqlalchemy.pool.Pool`, such as a
        :class:`~sqlalchemy.pool.QueuePool` instance. If non-None, this
        pool will be used directly as the underlying connection pool
        for the engine, bypassing whatever connection parameters are
        present in the URL argument. For information on constructing
        connection pools manually, see :ref:`pooling_toplevel`.

    :param poolclass=None: a :class:`~sqlalchemy.pool.Pool`
        subclass, which will be used to create a connection pool
        instance using the connection parameters given in the URL. Note
        this differs from ``pool`` in that you don't actually
        instantiate the pool in this case, you just indicate what type
        of pool to be used.

    :param pool_logging_name:  String identifier which will be used within
       the "name" field of logging records generated within the
       "sqlalchemy.pool" logger. Defaults to a hexstring of the object's
       id.

       .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.

    :param pool_pre_ping: boolean, if True will enable the connection pool
        "pre-ping" feature that tests connections for liveness upon
        each checkout.

        .. versionadded:: 1.2

        .. seealso::

            :ref:`pool_disconnects_pessimistic`

    :param pool_size=5: the number of connections to keep open
        inside the connection pool. This used with
        :class:`~sqlalchemy.pool.QueuePool` as
        well as :class:`~sqlalchemy.pool.SingletonThreadPool`.  With
        :class:`~sqlalchemy.pool.QueuePool`, a ``pool_size`` setting
        of 0 indicates no limit; to disable pooling, set ``poolclass`` to
        :class:`~sqlalchemy.pool.NullPool` instead.

    :param pool_recycle=-1: this setting causes the pool to recycle
        connections after the given number of seconds has passed. It
        defaults to -1, or no timeout. For example, setting to 3600
        means connections will be recycled after one hour. Note that
        MySQL in particular will disconnect automatically if no
        activity is detected on a connection for eight hours (although
        this is configurable with the MySQLDB connection itself and the
        server configuration as well).

        .. seealso::

            :ref:`pool_setting_recycle`

    :param pool_reset_on_return='rollback': set the
        :paramref:`_pool.Pool.reset_on_return` parameter of the underlying
        :class:`_pool.Pool` object, which can be set to the values
        ``"rollback"``, ``"commit"``, or ``None``.

        .. seealso::

            :ref:`pool_reset_on_return`

            :ref:`dbapi_autocommit_skip_rollback` - a more modern approach
            to using connections with no transactional instructions

    :param pool_timeout=30: number of seconds to wait before giving
        up on getting a connection from the pool. This is only used
        with :class:`~sqlalchemy.pool.QueuePool`. This can be a float but is
        subject to the limitations of Python time functions which may not be
        reliable in the tens of milliseconds.

        .. note: don't use 30.0 above, it seems to break with the :param tag

    :param pool_use_lifo=False: use LIFO (last-in-first-out) when retrieving
        connections from :class:`.QueuePool` instead of FIFO
        (first-in-first-out). Using LIFO, a server-side timeout scheme can
        reduce the number of connections used during non- peak   periods of
        use.   When planning for server-side timeouts, ensure that a recycle or
        pre-ping strategy is in use to gracefully   handle stale connections.

          .. versionadded:: 1.3

          .. seealso::

            :ref:`pool_use_lifo`

            :ref:`pool_disconnects`

    :param plugins: string list of plugin names to load.  See
        :class:`.CreateEnginePlugin` for background.

        .. versionadded:: 1.2.3

    :param query_cache_size: size of the cache used to cache the SQL string
     form of queries.  Set to zero to disable caching.

     The cache is pruned of its least recently used items when its size reaches
     N * 1.5.  Defaults to 500, meaning the cache will always store at least
     500 SQL statements when filled, and will grow up to 750 items at which
     point it is pruned back down to 500 by removing the 250 least recently
     used items.

     Caching is accomplished on a per-statement basis by generating a
     cache key that represents the statement's structure, then generating
     string SQL for the current dialect only if that key is not present
     in the cache.   All statements support caching, however some features
     such as an INSERT with a large set of parameters will intentionally
     bypass the cache.   SQL logging will indicate statistics for each
     statement whether or not it were pull from the cache.

     .. note:: some ORM functions related to unit-of-work persistence as well
        as some attribute loading strategies will make use of individual
        per-mapper caches outside of the main cache.


     .. seealso::

        :ref:`sql_caching`

     .. versionadded:: 1.4

    :param skip_autocommit_rollback: When True, the dialect will
       unconditionally skip all calls to the DBAPI ``connection.rollback()``
       method if the DBAPI connection is confirmed to be in "autocommit" mode.
       The availability of this feature is dialect specific; if not available,
       a ``NotImplementedError`` is raised by the dialect when rollback occurs.

       .. seealso::

            :ref:`dbapi_autocommit_skip_rollback`

       .. versionadded:: 2.0.43

    :param use_insertmanyvalues: True by default, use the "insertmanyvalues"
     execution style for INSERT..RETURNING statements by default.

     .. versionadded:: 2.0

     .. seealso::

        :ref:`engine_insertmanyvalues`

In [35]:
#mysql connection
#"mysql+mysqldb://scott:tiger@hostname/dbname"
# engine_mysql = create_engine("mysql+mysqldb://root:root@localhost:3306/walmart_db")
from sqlalchemy import create_engine

# Change 'mysqldb' to 'pymysql'
engine_mysql = create_engine("mysql+pymysql://root:root@localhost:3306/walmart_db")
try:
    engine_mysql
    print("connection Successed to mysql")
except:
    print("not connected")

connection Successed to mysql

In [31]:
help(df.to_sql)

Help on method to_sql in module pandas.core.generic:

to_sql(
    name: 'str',
    con,
    *,
    schema: 'str | None' = None,
    if_exists: "Literal['fail', 'replace', 'append', 'delete_rows']" = 'fail',
    index: 'bool' = True,
    index_label: 'IndexLabel | None' = None,
    chunksize: 'int | None' = None,
    dtype: 'DtypeArg | None' = None,
    method: "Literal['multi'] | Callable | None" = None
) -> 'int | None' method of pandas.DataFrame instance
    Write records stored in a DataFrame to a SQL database.

    Databases supported by SQLAlchemy [1]_ are supported. Tables can be
    newly created, appended to, or overwritten.

    .. warning::
        The pandas library does not attempt to sanitize inputs provided via a to_sql call.
        Please refer to the documentation for the underlying database driver to see if it
        will properly prevent injection, or alternatively be advised of a security risk when
        executing arbitrary commands in a to_sql call.

    Parameters
    ----------
    name : str
        Name of SQL table.
    con : ADBC connection, sqlalchemy.engine.(Engine or Connection) or sqlite3.Connection
        ADBC provides high performance I/O with native type support, where available.
        Using SQLAlchemy makes it possible to use any DB supported by that
        library. Legacy support is provided for sqlite3.Connection objects. The user
        is responsible for engine disposal and connection closure for the SQLAlchemy
        connectable. See `here                 <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
        If passing a sqlalchemy.engine.Connection which is already in a transaction,
        the transaction will not be committed.  If passing a sqlite3.Connection,
        it will not be possible to roll back the record insertion.

    schema : str, optional
        Specify the schema (if database flavor supports this). If None, use
        default schema.
    if_exists : {'fail', 'replace', 'append', 'delete_rows'}, default 'fail'
        How to behave if the table already exists.

        * fail: Raise a ValueError.
        * replace: Drop the table before inserting new values.
        * append: Insert new values to the existing table.
        * delete_rows: If a table exists, delete all records and insert data.

    index : bool, default True
        Write DataFrame index as a column. Uses `index_label` as the column
        name in the table. Creates a table index for this column.
    index_label : str or sequence, default None
        Column label for index column(s). If None is given (default) and
        `index` is True, then the index names are used.
        A sequence should be given if the DataFrame uses MultiIndex.
    chunksize : int, optional
        Specify the number of rows in each batch to be written to the database connection at a time.
        By default, all rows will be written at once. Also see the method keyword.
    dtype : dict or scalar, optional
        Specifying the datatype for columns. If a dictionary is used, the
        keys should be the column names and the values should be the
        SQLAlchemy types or strings for the sqlite3 legacy mode. If a
        scalar is provided, it will be applied to all columns.
    method : {None, 'multi', callable}, optional
        Controls the SQL insertion clause used:

        * None : Uses standard SQL ``INSERT`` clause (one per row).
        * 'multi': Pass multiple values in a single ``INSERT`` clause.
        * callable with signature ``(pd_table, conn, keys, data_iter)``.

        Details and a sample callable implementation can be found in the
        section :ref:`insert method <io.sql.method>`.

    Returns
    -------
    None or int
        Number of rows affected by to_sql. None is returned if the callable
        passed into ``method`` does not return an integer number of rows.

        The number of returned rows affected is the sum of the ``rowcount``
        attribute of ``sqlite3.Cursor`` or SQLAlchemy connectable which may not
        reflect the exact number of written rows as stipulated in the
        `sqlite3 <https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.rowcount>`__ or
        `SQLAlchemy <https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.rowcount>`__.

    Raises
    ------
    ValueError
        When the table already exists and `if_exists` is 'fail' (the
        default).

    See Also
    --------
    read_sql : Read a DataFrame from a table.

    Notes
    -----
    Timezone aware datetime columns will be written as
    ``Timestamp with timezone`` type with SQLAlchemy if supported by the
    database. Otherwise, the datetimes will be stored as timezone unaware
    timestamps local to the original timezone.

    Not all datastores support ``method="multi"``. Oracle, for example,
    does not support multi-value insert.

    References
    ----------
    .. [1] https://docs.sqlalchemy.org
    .. [2] https://www.python.org/dev/peps/pep-0249/

    Examples
    --------
    Create an in-memory SQLite database.

    >>> from sqlalchemy import create_engine
    >>> engine = create_engine('sqlite://', echo=False)

    Create a table from scratch with 3 rows.

    >>> df = pd.DataFrame({'name' : ['User 1', 'User 2', 'User 3']})
    >>> df
         name
    0  User 1
    1  User 2
    2  User 3

    >>> df.to_sql(name='users', con=engine)
    3
    >>> from sqlalchemy import text
    >>> with engine.connect() as conn:
    ...     conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 1'), (1, 'User 2'), (2, 'User 3')]

    An `sqlalchemy.engine.Connection` can also be passed to `con`:

    >>> with engine.begin() as connection:
    ...     df1 = pd.DataFrame({'name' : ['User 4', 'User 5']})
    ...     df1.to_sql(name='users', con=connection, if_exists='append')
    2

    This is allowed to support operations that require that the same
    DBAPI connection is used for the entire operation.

    >>> df2 = pd.DataFrame({'name' : ['User 6', 'User 7']})
    >>> df2.to_sql(name='users', con=engine, if_exists='append')
    2
    >>> with engine.connect() as conn:
    ...     conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 1'), (1, 'User 2'), (2, 'User 3'),
     (0, 'User 4'), (1, 'User 5'), (0, 'User 6'),
     (1, 'User 7')]

    Overwrite the table with just ``df2``.

    >>> df2.to_sql(name='users', con=engine, if_exists='replace',
    ...            index_label='id')
    2
    >>> with engine.connect() as conn:
    ...     conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 6'), (1, 'User 7')]

    Delete all rows before inserting new records with ``df3``

    >>> df3 = pd.DataFrame({"name": ['User 8', 'User 9']})
    >>> df3.to_sql(name='users', con=engine, if_exists='delete_rows',
    ...            index_label='id')
    2
    >>> with engine.connect() as conn:
    ...     conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 8'), (1, 'User 9')]

    Use ``method`` to define a callable insertion method to do nothing
    if there's a primary key conflict on a table in a PostgreSQL database.

    >>> from sqlalchemy.dialects.postgresql import insert
    >>> def insert_on_conflict_nothing(table, conn, keys, data_iter):
    ...     # "a" is the primary key in "conflict_table"
    ...     data = [dict(zip(keys, row)) for row in data_iter]
    ...     stmt = insert(table.table).values(data).on_conflict_do_nothing(index_elements=["a"])
    ...     result = conn.execute(stmt)
    ...     return result.rowcount
    >>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append",  # noqa: F821
    ...                    method=insert_on_conflict_nothing)  # doctest: +SKIP
    0

    For MySQL, a callable to update columns ``b`` and ``c`` if there's a conflict
    on a primary key.

    >>> from sqlalchemy.dialects.mysql import insert   # noqa: F811
    >>> def insert_on_conflict_update(table, conn, keys, data_iter):
    ...     # update columns "b" and "c" on primary key conflict
    ...     data = [dict(zip(keys, row)) for row in data_iter]
    ...     stmt = (
    ...         insert(table.table)
    ...         .values(data)
    ...     )
    ...     stmt = stmt.on_duplicate_key_update(b=stmt.inserted.b, c=stmt.inserted.c)
    ...     result = conn.execute(stmt)
    ...     return result.rowcount
    >>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append",  # noqa: F821
    ...                    method=insert_on_conflict_update)  # doctest: +SKIP
    2

    Specify the dtype (especially useful for integers with missing values).
    Notice that while pandas is forced to store the data as floating point,
    the database supports nullable integers. When fetching the data with
    Python, we get back integer scalars.

    >>> df = pd.DataFrame({"A": [1, None, 2]})
    >>> df
         A
    0  1.0
    1  NaN
    2  2.0

    >>> from sqlalchemy.types import Integer
    >>> df.to_sql(name='integers', con=engine, index=False,
    ...           dtype={"A": Integer()})
    3

    >>> with engine.connect() as conn:
    ...     conn.execute(text("SELECT * FROM integers")).fetchall()
    [(1,), (None,), (2,)]

    .. versionadded:: 2.2.0

       pandas now supports writing via ADBC drivers

    >>> df = pd.DataFrame({'name' : ['User 10', 'User 11', 'User 12']})
    >>> df
          name
    0  User 10
    1  User 11
    2  User 12

    >>> from adbc_driver_sqlite import dbapi  # doctest:+SKIP
    >>> with dbapi.connect("sqlite://") as conn:  # doctest:+SKIP
    ...     df.to_sql(name="users", con=conn)
    3

In [36]:
df.to_sql(name='walmart',con=engine_mysql,if_exists='append',index=False)

9969

In [37]:
df.shape

(9969, 12)